#!/bin/bash

# Calculates coding density of genome from prokka output.
# Requires 2 arguments: 1) .tsv file; 2) .fsa file,
# both of which are generated by prokka

coding=`grep 'CDS' $1 | awk '{sum += $3;} END {print sum;}'`
full=`grep -v '>' $2 | tr -d '\n' | wc -c `
echo "scale=2; 100* $coding / $full" | bc
